Repository onnx/ir-py, pull requests merged in 2025-08, with the labels that each got.

#145 Fix support for torch.float8_e8m0fnu for older versions of PyTorch
  src/onnx_ir/tensor_adapters.py
  src/onnx_ir/tensor_adapters_test.py
Labels: topic: bug fix

#147 Fix a typo in NameFixPass docs
  src/onnx_ir/passes/common/naming.py
Labels: module: docs

#158 Expose the graph properly in `ir.Function`
  src/onnx_ir/_core.py
Labels: module: api

#159 Update node deser logic to support out of order subgraphs
  src/onnx_ir/serde.py
  src/onnx_ir/serde_test.py
Labels: module: core

#163 Expose DeduplicateHashedInitializersPass
  src/onnx_ir/passes/common/__init__.py
  src/onnx_ir/passes/common/identity_elimination.py
Labels: module: api

#169 Support string tensors in DeduplicateInitializersPass and call_onnx_api
  src/onnx_ir/_core.py
  src/onnx_ir/_core_test.py
  src/onnx_ir/_enums.py
  src/onnx_ir/passes/common/initializer_deduplication.py
  src/onnx_ir/passes/common/initializer_deduplication_test.py
Labels: module: passes

#69 Create diagram for IR objects
  README.md
  REUSE.toml
  docs/resource/onnx-ir-entities.svg
  docs/resource/onnx_ir_entities.excalidraw
Labels: module: docs
