Repository onnx/ir-py, pull requests merged in 2025-09, with the labels that each got.

#171 Add more properties for numeric types to DataType
  src/onnx_ir/_enums.py
Labels: module: api

#175 [serde] Cast attribute values to int or float
  src/onnx_ir/serde.py
  src/onnx_ir/serde_test.py
Labels: topic: bug fix

#177 Add missing .. versionadded:: for DataType.is_string
  src/onnx_ir/_enums.py
Labels: module: docs

#178 Ensure int/float attributes are stored as Python int/float
  src/onnx_ir/_convenience/__init__.py
  src/onnx_ir/_core.py
  src/onnx_ir/_core_test.py
  src/onnx_ir/serde.py
  src/onnx_ir/serde_test.py
Labels: module: api

#184 Support deserializing non-utf8 attributes in rare case
  src/onnx_ir/serde.py
Labels: module: core

#179 Create a convenience constructor for Value
  docs/api/core.md
  src/onnx_ir/__init__.py
  src/onnx_ir/_convenience/_constructors.py
  src/onnx_ir/_convenience/_constructors_test.py
Labels: module: api

#197 Update the graph initializers dictionary when renaming Value
  src/onnx_ir/_core.py
  src/onnx_ir/_core_test.py
  src/onnx_ir/passes/common/naming.py
Labels: module: api

#203 Handle when the value type is not known when serializing shapes
  src/onnx_ir/serde.py
  src/onnx_ir/serde_test.py
Labels: topic: bug fix
